### Read excel files

In [81]:
from pathlib import Path
import pandas as pd

archivo = Path(
    "data/raw/vaccine_coverage/"
    "Coberturas de Vacunacion Municipal desde 1998-2025(30-01-2025).xlsx"
)
if not archivo.is_file():
    archivo = Path("..") / archivo

coberturas = {}
columnas_poblacion = {
    2015: ["Poblaciòn de 1 año (Meta varicela media cohorte)"],
    2016: ["Poblaciòn de 1 año Meta Programática)"],
    2017: ["Poblaciòn de 1 año Meta Programática)"],
    2018: ["Poblaciòn de 1 año Meta Programática)"],
    2019: [
        "Poblaciòn de 1 año Meta Programática)",
        "Pob. 5 años  (Meta Programatica)",
    ],
    2020: [
        "Poblaciòn de 1 año (Meta Programática 2020)",
        "Pob. 5 años  (Meta Programática 2020)",
    ],
    2021: [
        "Poblaciòn de 1 año (Meta Programática 2021)",
        "Pob. 5 años  (Meta Programática 2021)",
    ],
    2022: [
        "Poblaciòn de 1 año (Meta Programática 2022)",
        "Pob. 5 años  (Meta Programática 2022)",
    ],
    2023: [
        "POB. 1 año\nMETA PROGRAM 2023",
        "POB. 5 Años\nMETA PROGRAM 2023",
    ],
    2024: [
        "POB. 1 año\nMETA PROGRAMATICA\n2024 (Aj2_20241028)",
        "POB. 5 Años\nMETA PROGRAMATICA 2024 (Aj2_20241028)",
    ],
    2025: [
        "POB. < 1 AÑO\nMETA PROGRAMATICA\n2025 (20251130)VerF",
        "POB. 5 Años\nMETA PROGRAMATICA 2025 (20251130)VerF",
    ],
}

with pd.ExcelFile(archivo) as excel:
    for anio in range(2015, 2026):
        fila_header = 6 if anio == 2016 else 5

        ultima_fila = 1128 if anio == 2016 else 1127

        df = pd.read_excel(
            excel,
            sheet_name=str(anio),
            header=fila_header - 1,
            nrows=ultima_fila - fila_header,
            dtype={"CODEP": "string", "DIVIPOLA": "string"},
        )
        columnas_base = df.columns[1:5] if anio in (2016, 2017) else df.columns[:4]
        columnas_varicela = [
            col for col in df.columns if "VARICELA" in str(col).upper()
        ]
        metas = columnas_poblacion[anio]

        columnas = list(dict.fromkeys([
            *columnas_base,
            *metas,
            *columnas_varicela,
        ]))

        nombres_metas = ["meta_pob_1_anio", "meta_pob_5_anios"]
        renombrar = dict(zip(metas, nombres_metas))

        coberturas[anio] = df.loc[:, columnas].rename(columns=renombrar).copy()

for anio, df in coberturas.items():
    print(anio, df.shape)

display(coberturas[2025].head())

2015 (1122, 7)
2016 (1122, 7)
2017 (1122, 7)
2018 (1122, 7)
2019 (1122, 10)
2020 (1122, 10)
2021 (1122, 10)
2022 (1122, 10)
2023 (1122, 10)
2024 (1122, 10)
2025 (1122, 11)

,CODEP,Nombre_ET,DIVIPOLA,Municipio,meta_pob_1_anio,meta_pob_5_anios,VARICELA DE 1 AÑO\nD. Unica,% VARICELA DE 1 AÑO,VARICELA DE 5 AÑOS Ref.,% VARICELA,% Varicela\n5 Años
0,05,ANTIOQUIA,05001,Medellin,17429,22817,15935,85.8,14964,65.6,65.6
1,05,ANTIOQUIA,05002,Abejorral,127,166,127,85.3,147,88.6,88.6
2,05,ANTIOQUIA,05004,Abriaqui,12,21,10,71.5,16,76.2,76.2
3,05,ANTIOQUIA,05021,Alejandria,32,44,32,114.3,43,97.8,97.8
4,05,ANTIOQUIA,05030,Amaga,198,240,196,87.5,206,85.9,85.9

In [82]:
display(coberturas[2021].columns)

Index(['CODEP', 'Nombre_ET', 'DIVIPOLA', 'Municipio', 'meta_pob_1_anio',
       'meta_pob_5_anios', 'VARICELA DE 1 AÑO\nD. Unica',
       '% VARICELA DE 1 AÑO', 'VARICELA DE 5 AÑOS Ref.', '% VARICELA'],
      dtype='str')

In [83]:
display(coberturas[2025].columns)

Index(['CODEP', 'Nombre_ET', 'DIVIPOLA', 'Municipio', 'meta_pob_1_anio',
       'meta_pob_5_anios', 'VARICELA DE 1 AÑO\nD. Unica',
       '% VARICELA DE 1 AÑO', 'VARICELA DE 5 AÑOS Ref.', '% VARICELA',
       '% Varicela\n5 Años '],
      dtype='str')

In [84]:
for anio, df in coberturas.items():
    print(anio, "___", ", ".join(coberturas[anio]))

2015 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, VARICELA DE 1 AÑO
1a, % VARICELA DE 1 AÑO - Cump AGOSTO
2016 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO
2017 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO
2018 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO
2019 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS, % VARICELA
2020 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA
2021 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA
2022 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA
2023 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA
2024 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA
2025 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, VARICELA DE 1 AÑO
D. Unica, % VARICELA DE 1 AÑO, VARICELA DE 5 AÑOS Ref., % VARICELA, % Varicela
5 Años

In [85]:
coberturas[2015] = coberturas[2015].rename(
    columns={"VARICELA DE 1 AÑO\n1a": "varicela_un_anio_dosis_unica",
             "% VARICELA DE 1 AÑO - Cump AGOSTO": "%_varicela_un_anio_dosis_unica"}
)
for anio in range(2016,2026):
    coberturas[anio] = coberturas[anio].rename(
        columns={"VARICELA DE 1 AÑO\nD. Unica": "varicela_un_anio_dosis_unica",
                 "% VARICELA DE 1 AÑO": "%_varicela_un_anio_dosis_unica"
                 }
    )


for anio in range(2019,2026):
    coberturas[anio] = coberturas[anio].rename(
        columns={"VARICELA DE 5 AÑOS Ref.": "varicela_cinco_anios_refuerzo",
                 "% VARICELA": "%_varicela_cinco_anios_refuerzo"

                 }
    )

coberturas[2019] = coberturas[2019].rename(
    columns={"VARICELA DE 5 AÑOS": "varicela_cinco_anios_refuerzo"}
)

coberturas[2025] = coberturas[2025].drop(
    columns=["% Varicela\n5 Años "]
)

for anio in range(2015,2019):
    coberturas[anio]["meta_pob_5_anios"] = pd.NA
    coberturas[anio]["varicela_cinco_anios_refuerzo"] = pd.NA
    coberturas[anio]["%_varicela_cinco_anios_refuerzo"] = pd.NA

In [86]:
for anio, df in coberturas.items():
    print(anio, "___", ", ".join(coberturas[anio]))

2015 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, meta_pob_5_anios, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2016 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, meta_pob_5_anios, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2017 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, meta_pob_5_anios, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2018 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, meta_pob_5_anios, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2019 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2020 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2021 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2022 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2023 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2024 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo
2025 ___ CODEP, Nombre_ET, DIVIPOLA, Municipio, meta_pob_1_anio, meta_pob_5_anios, varicela_un_anio_dosis_unica, %_varicela_un_anio_dosis_unica, varicela_cinco_anios_refuerzo, %_varicela_cinco_anios_refuerzo

In [80]:
print(",".join(coberturas[2025].columns))

CODEP,Nombre_ET,DIVIPOLA,Municipio,meta_pob_1_anio,meta_pob_5_anios,varicela_un_anio_dosis_unica,%_varicela_un_anio_dosis_unica,varicela_cinco_anios_refuerzo,%_varicela_cinco_anios_refuerzo

In [87]:
coberturas_all = pd.concat(
    [
        df.assign(anio=anio)
        for anio, df in sorted(coberturas.items())
    ],
    ignore_index=True,
    sort=False,
)

display(coberturas_all.head())
print(coberturas_all.shape)

,CODEP,Nombre_ET,DIVIPOLA,Municipio,meta_pob_1_anio,varicela_un_anio_dosis_unica,%_varicela_un_anio_dosis_unica,meta_pob_5_anios,varicela_cinco_anios_refuerzo,%_varicela_cinco_anios_refuerzo,anio
0,05,ANTIOQUIA,05001,Medellin,13884.5,13918.0,100.2,<NA>,<NA>,<NA>,2015
1,05,ANTIOQUIA,05002,Abejorral,120.5,84.0,69.7,<NA>,<NA>,<NA>,2015
2,05,ANTIOQUIA,05004,Abriaqui,13.0,18.0,138.5,<NA>,<NA>,<NA>,2015
3,05,ANTIOQUIA,05021,Alejandria,29.5,29.0,98.3,<NA>,<NA>,<NA>,2015
4,05,ANTIOQUIA,05030,Amaga,141.0,128.0,90.8,<NA>,<NA>,<NA>,2015

(12342, 11)

In [88]:
# Dado que cada año corresponde a los datos publicados a diciembre de ese año lo cual tiene un lag de casi un año. Por lo cual, como en el
# trabajo Sato, R., Makinde, O. A., Daam, K. C., & Lawal, B. (2022), con el fin de reducir la causalidad inversa (reverse causality),
# es decir, evitar que un aumento de casos en el periodo actual produzca una respuesta de vacunación en ese mismo periodo y luego
# parezca que la vacunación está asociada con más casos; Se trabajará con un lag de un año
# por ejemplo, los casos de 2024 se les asignará la cobertura reportada en diciembre de 2023, que tienen asignado el año 2023 pero se
# reasignara al año 2024, por lo cual el año 2025 no se utilizará
coberturas_all = coberturas_all.loc[
    coberturas_all["anio"] != 2025
    ].copy()

coberturas_all["anio"] += 1

In [90]:
display(
    coberturas_all[["anio"]]
    .drop_duplicates()
    .sort_values("anio")
    .reset_index(drop=True)
)

   anio
0  2016
1  2017
2  2018
3  2019
4  2020
5  2021
6  2022
7  2023
8  2024
9  2025

In [91]:

carpeta_salida = archivo.parents[2] / "processed" / "vaccine_coverage"
carpeta_salida.mkdir(parents=True, exist_ok=True)

ruta_csv = carpeta_salida / "coberturas_municipales_2016_2025.csv"
coberturas_all.to_csv(ruta_csv, index=False, encoding="utf-8-sig")

print(f"Guardado en: {ruta_csv}")

Guardado en: ../data/processed/vaccine_coverage/coberturas_municipales_2016_2025.csv